services:
  - type: web
    name: paw-adopt
    env: php
    plan: free
    buildCommand: ""
    startCommand: "apache2-foreground"
    envVars:
      - key: APP_URL
        fromService:
          name: paw-adopt
          type: web
          envVarKey: RENDER_EXTERNAL_URL
