services:
services:
  - type: web
    name: pawadopt
    runtime: docker
    envVars:
      - key: DB_HOST
        value: your-aiven-host-here
      - key: DB_USER
        value: your-username
      - key: DB_PASS
        sync: false 
        value: your-password
      - key: DB_NAME
        value: your-database-name